---
- hosts: localhost
  become: true
  tasks:
    - name: Read package list file
      shell: cat /root/.ansible/pull/localhost/meta/install-list/apt
      register: output

    - name: Install packages
      apt:
        name: "{{ output.stdout_lines }}"
        state: latest



