---
- name: Read package list
  ansible.builtin.slurp:
    src: /root/.ansible/pull/localhost/meta/install-list/apt
  register: _apt_list_raw

- name: Install packages
  ansible.builtin.apt:
    name: >-
      {{
        (_apt_list_raw.content | b64decode).splitlines()
        | reject('match', '^\\s*(#.*)?$')
        | list
      }}
    state: present
    update_cache: true
